import { Story } from '@/types'

export const stories: Story[] = [
  {
    id: 'edinburgh-ilk-gun',
    title: 'Edinburgh\'ta İlk Gün',
    subtitle: 'Taş kokularda tarihin içine düşmek',
    city: 'Edinburgh',
    country: 'Birleşik Krallık',
    summary: 'Uçaktan indiğimizde kasvetli bir gökyüzü bekliyordu bizi. Ama Edinburgh sizi ilk günden kendine alıyor. Havalimanından City Centre\'e giderken araçtan izlediğim ilk manzara, o anı bir daha yaşamak isteyeceğimi bana söyledi.',
    coverImage: 'https://images.unsplash.com/photo-1530841377377-3ff06c0ca713?w=900&q=80',
    readTime: 5,
    publishedAt: '2023-09-15',
    tags: ['Edinburgh', 'İngiltere', 'Tarih', 'Aile'],
    featured: true,
  },
  {
    id: 'manchester-birakanlar',
    title: 'Manchester\'ın Bıraktığı His',
    subtitle: 'Müzik, yağmur ve Mancunian ruhu',
    city: 'Manchester',
    country: 'Birleşik Krallık',
    summary: 'Northern Quarter\'ın gürültülü sessizliğinde oturmuş, vinyl kayıt dinlerken bana Manchester\'ın sırrını anlattılar: Bu şehir sizi sevmeyebilir ama siz onu her zaman seversiniz.',
    coverImage: 'https://images.unsplash.com/photo-1520338661359-5e503b04e7b3?w=900&q=80',
    readTime: 4,
    publishedAt: '2023-09-18',
    tags: ['Manchester', 'Müzik', 'Kültür', 'Sokak'],
    featured: true,
  },
  {
    id: 'liverpool-muzik-futbol',
    title: 'Liverpool\'da Müzik ve Futbol',
    subtitle: 'Bir şehrin iki tutkusu, tek bir kalp',
    city: 'Liverpool',
    country: 'Birleşik Krallık',
    summary: 'Albert Dock\'ta yürürken anladım: Liverpool insanları diğer İngilizlerden farklı. Sıcaklar, gülerler ve sizi hep birinin daha davet ettiği yerlere yönlendirirler. Kavern Club\'ın merdivenlerinde inerken, tarihin içine kayıyordum.',
    coverImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=80',
    readTime: 6,
    publishedAt: '2023-09-21',
    tags: ['Liverpool', 'Beatles', 'Futbol', 'Liman'],
    featured: true,
  },
  {
    id: 'hollanda-sokaklarinda',
    title: 'Hollanda Sokaklarında',
    subtitle: 'Kanallar, bisikletler ve sakin bir özgürlük',
    city: 'Amsterdam',
    country: 'Hollanda',
    summary: 'Amsterdam\'ı yüzlerce kez hayal ettim. Gerçek, hayalden daha güzeldi. Sabah 6\'da kiraladığım bisikletle Jordaan\'ı dolaştım; şehir henüz uyanmamıştı ve o an sadece bana aitti.',
    coverImage: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=900&q=80',
    readTime: 5,
    publishedAt: '2023-10-05',
    tags: ['Amsterdam', 'Hollanda', 'Bisiklet', 'Özgürlük'],
    featured: true,
  },
  {
    id: 'paris-kaybolmak',
    title: 'Paris\'te Kaybolmak',
    subtitle: 'Her sokak bir şiir, her kafe bir film',
    city: 'Paris',
    country: 'Fransa',
    summary: 'Haritayı bir kenara bırakıp Montmartre sokaklarında gezmek, yan sokakta ansızın bir şarap dükkânıyla karşılaşmak, yaşlı bir adamın sizi selamlayıp geçmesi... Paris\'in tadı böyle çıkıyor.',
    coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=900&q=80',
    readTime: 7,
    publishedAt: '2023-11-12',
    tags: ['Paris', 'Fransa', 'Romantik', 'Yürüyüş'],
    featured: false,
  },
  {
    id: 'barcelona-gece',
    title: 'Barcelona\'nın Gecesi',
    subtitle: 'Gün battıktan sonra asıl şehir uyanır',
    city: 'Barcelona',
    country: 'İspanya',
    summary: 'Barselona\'yı gündüz gezersiniz ama geceyi yaşarsınız. Sagrada Familia\'nın gece aydınlatması, Gothic Quarter\'ın ıssız sokaklarında gölgeler, limanda şarap...',
    coverImage: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=900&q=80',
    readTime: 5,
    publishedAt: '2024-03-20',
    tags: ['Barcelona', 'İspanya', 'Gece', 'Gastronomı'],
    featured: false,
  },
]
